sudo: required
services:
  - docker

before_install:
  - docker build -t nafzaltx/docker-react-nov2019 -f Dockerfile.dev .

script:
  - docker run -e CI=true nafzaltx/docker-react-nov2019 npm run test
